name: eval and publish notebook

on:
  schedule:
    - cron: "0 8 * * *" # everyday at 8am

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_forecast:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: create python env
        run: |
          conda create -y --name py37 python=3.7
      - name: initialize conda
        run: bash -c "conda init bash"
      - name: activate env
        run: bash -c "conda init bash && conda activate py37"
      - name: install dependencies
        run: bash -c "conda install -c conda-forge --file requirements.txt"
      - name: install Pydap
        run: pip install Pydap
      - name: Complete listing of data dirs
        if: ${{ always() }}
        run: |
          du -sh *
      - name: Convert to HTML
        if: ${{ always() }}
        run: |
          jupyter nbconvert --execute automatic_time_series_SST.ipynb --to html

      - name: Upload notebook
        uses: actions/upload-artifact@v1
        if: ${{ always() }}
        with:
          name: ci_out
          path: ci_out/
      - name: Prepare pages
        run: |
          mkdir -p ./public
          cp ci_out/*.html ./public/.
          echo '<meta HTTP-EQUIV="REFRESH" content="0; url=automatic_time_series_SST.html">' > ./public/index.html
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
